# docker-compose.yml
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - backtier
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://batuhan:password@db:5432/ecommerce
  db:
    image: postgres:latest
    restart: always
    networks:
      - backtier
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
volumes:
  postgres:

networks:
  backtier:









